export { default as Home } from "@/pages/dashboard/home";
export { default as DataBarang } from "@/pages/dashboard/databarang"; // Pastikan DataBarang diekspor
export { default as TablesMaintenance } from "@/pages/dashboard/tablesmaintenance";
export { default as CCTV } from "@/pages/dashboard/cctv";
export { default as KomputerPH1 } from "@/pages/dashboard/komputer-ph1";
export { default as KomputerPH2 } from "@/pages/dashboard/komputer-ph2";
export { default as Fingerprint } from "@/pages/dashboard/fingerprint";
export { default as Printer } from "@/pages/dashboard/printer";
export { default as Telepon } from "@/pages/dashboard/telepon";
export { default as TOA } from "@/pages/dashboard/toa";
export { default as UPS } from "@/pages/dashboard/ups";
export { default as AddTOA } from "@/pages/dashboard/add/addtoa";
export { default as addUPS } from "@/pages/dashboard/add/addups";
export { default as addprinter } from "@/pages/dashboard/add/addprinter";
export { default as AddCCTV } from "@/pages/dashboard/add/addcctv";
export { default as AddTelepon } from "@/pages/dashboard/add/addtelepon";
export { default as AddFingerprint } from "@/pages/dashboard/add/addfingerprint";
export { default as AddKomputerPH1} from "@/pages/dashboard/add/addkomputerph1";
export { default as AddKomputerPH2} from "@/pages/dashboard/add/addkomputerph2";
export { default as EditTOA } from "@/pages/dashboard/edit/edittoa";
export { default as EditUPS } from "@/pages/dashboard/edit/editups";
export { default as EditPrinter } from "@/pages/dashboard/edit/editprinter";
export { default as EditCCTV } from "@/pages/dashboard/edit/editcctv";
export { default as EditTelepon } from "@/pages/dashboard/edit/edittelepon";
export { default as EditFingerprint } from "@/pages/dashboard/edit/editfingerprint";
export { default as EditKomputerPH1 } from "@/pages/dashboard/edit/editkomputerph1";
export { default as EditKomputerPH2 } from "@/pages/dashboard/edit/editkomputerph2";
export { default as MaintenanceCCTV } from "@/pages/dashboard/maintenance-cctv";
export { default as MaintenanceListCCTV } from "@/pages/dashboard/maintenance-list-cctv";
export { default as CheckpointCCTV } from "@/pages/dashboard/checkpoint-cctv.jsx";